import type { Tweet } from "./tweet";

/* Real tweets scraped from ui.aceternity.com's community wall (placeholder
   content until Lunar Studio has its own) — avatars served from Twitter's CDN. */
export const TWEETS: Tweet[] = [
  {
    profile_image: "https://pbs.twimg.com/profile_images/1816814706000080897/uSIidPHz_200x200.png",
    username: "peer_rich",
    comment: "amazing to see @calcom find its way into proper templates 🥳\n\nexcited to be powering the next thousands of startups and their demo calls!",
    blue_tick: true,
    fullname: "Peer Richelsen",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1984249830525501440/94QR6rln_200x200.jpg",
    username: "striver_79",
    comment: "Just checked out Aceternity (UX components), great work done by @mannupaaji \n\nLooks premium, top notch 🧨",
    blue_tick: true,
    fullname: "Striver | Building takeUforward",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1777768083803037697/uGk8lU2y_200x200.jpg",
    username: "Teddarific",
    comment: "Wow, this site is an ABSOLUTE GOLDMINE for design engineers.\n\nIt's a huge collection of micro-interactions / animations, all with their respective source code for you to copy and paste.\n\nLove to see such an amazing display of my favorite package, framer-motion",
    blue_tick: true,
    fullname: "Teddy Ni",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/2039941295167397888/JcSt21Xy_200x200.jpg",
    username: "geekpreneur_",
    comment: "Looking absolutely awesome ! 👏",
    blue_tick: true,
    fullname: "Jerem",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1665455114616700930/T8JjwdQy_200x200.jpg",
    username: "mjakupiiii",
    comment: "Amazing 🚀",
    blue_tick: true,
    fullname: "metinn",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/2065178790293299200/3MWmwVGy_200x200.jpg",
    username: "rh_rahat_dev",
    comment: "Absolutely Awesome, Would really love to use some of these in my projects",
    blue_tick: true,
    fullname: "Rayhan Rahat",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/2050494347523833856/XoYEiZ1o_200x200.jpg",
    username: "rexan_wong",
    comment: "🔖 Bookmarking it right away",
    blue_tick: true,
    fullname: "Rexan Wong",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1588546984977338368/-MkIqxOl_200x200.jpg",
    username: "sus6461",
    comment: "is amazing ❤️‍🔥❤️‍🔥\nIt is open forever?",
    blue_tick: false,
    fullname: "sus646",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1689278735843799040/pZplvIad_200x200.jpg",
    username: "InLessimore",
    comment: "I really like it.I will try to use it my next app",
    blue_tick: false,
    fullname: "iOS/MacOS Developer | Swift | Xcode",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1396375667529244676/o9VxEoTq_200x200.jpg",
    username: "PaarthAgarwal17",
    comment: "I just tried it out this is crazy awesome",
    blue_tick: false,
    fullname: "Paarth Agarwal",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1932562415293538304/VqirCJVI_200x200.jpg",
    username: "Yousefcopy",
    comment: "Looks sick 👌🏼",
    blue_tick: true,
    fullname: "Yousef",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1606494029453328384/sUkvtpO__200x200.jpg",
    username: "oamarkanji",
    comment: "Man this is awesome",
    blue_tick: true,
    fullname: "Oamar",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1371347197313175554/mUp6R7_G_200x200.jpg",
    username: "rajdeepseth1",
    comment: "Stumbled upon ui.aceternity.com today and my mind is blown 🤯 \nThe seamless integration of framer-motion, tailwind CSS, and shadcn showcases a masterclass in UI design. 🚀 Kudos to @mannupaaji for creating such an innovative and inspirational resource for devs! #UI #nextjs",
    blue_tick: false,
    fullname: "Rajdeep Seth",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/2021307607957327872/qsS9-rAr_200x200.jpg",
    username: "jsmasterypro",
    comment: "Have you heard of Aceternity UI? \n\nIt's packed with various animated components that are ready to copy and paste! Mind-blowing stuff... 🤯\n\nClick here ➡️ ui.aceternity.com\n\n#framermotion #nextjs #tailwindcss #techinnovation",
    blue_tick: true,
    fullname: "Adrian | JavaScript Mastery",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1957737906837110784/14pXLrLa_200x200.jpg",
    username: "rajeshdavidbabu",
    comment: "ui.aceternity.com\n\nSo well done. And its bloody free 🤯🤯\n\nPhenomenal work by  @mannupaaji",
    blue_tick: false,
    fullname: "Rajesh David",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1963713890048708608/PNJFIukN_200x200.jpg",
    username: "Codydearkland",
    comment: "This library is so dope. Stoked to see more components drop.",
    blue_tick: true,
    fullname: "Cody De Arkland",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/2025424976375869440/OgySAub0_200x200.jpg",
    username: "Rasmic",
    comment: "Yoo.... This has to be the most beautiful component library I've ever seen!!\n\nui.aceternity.com\n\nShoutout to @mannupaaji for releasing this for free!",
    blue_tick: true,
    fullname: "Micky",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1863955384408358912/yI-TiwSz_200x200.jpg",
    username: "PatniShubh",
    comment: "bro just keeps dropping crazy alpha",
    blue_tick: true,
    fullname: "shubh",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1722358890807861248/75S7CB3G_200x200.jpg",
    username: "gregberge_",
    comment: "It’s awesome 👏",
    blue_tick: false,
    fullname: "Greg Bergé",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1748597109924798464/olncJkoo_200x200.jpg",
    username: "ajayvignesh01",
    comment: "Wow, this is awesome!",
    blue_tick: true,
    fullname: "Ajay",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/2029916844350709760/GjltGaED_200x200.jpg",
    username: "rum_ovo_xo",
    comment: "I like the interaction and animation. Beautiful!",
    blue_tick: false,
    fullname: "RD",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1722358890807861248/75S7CB3G_200x200.jpg",
    username: "gregberge_",
    comment: "✨ Aceternity UI is a complete collections of stunning effects ready to used for your website. It's shadcn/ui for magic effects. Can't believe it's free!\n\n👉 ui.aceternity.com",
    blue_tick: false,
    fullname: "Greg Bergé",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1984763429148905472/6ntPfs3t_200x200.jpg",
    username: "dncandia",
    comment: "This is absolutely mind blowing.\nAnimated UIs are the big leap forward on modern interfaces. Already thinking on how to build our website using these 💡",
    blue_tick: true,
    fullname: "Nahuel Candia",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1986831169493651459/3c4Ps8Mw_200x200.jpg",
    username: "hackmamba",
    comment: "This is awesome 👏",
    blue_tick: true,
    fullname: "Hackmamba",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1828192492187009024/AAh_6um3_200x200.jpg",
    username: "SeanBrydon13",
    comment: "Wow all for free! Setup a tip jar or buy me a coffee! I’d paid or this",
    blue_tick: true,
    fullname: "Sean brydon",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1883875248099000320/IxUfmCOn_200x200.jpg",
    username: "enisdev",
    comment: "Bro this is too beautiful, why is this even free??",
    blue_tick: false,
    fullname: "Enis",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/2047574253424513024/GN8P4uuX_200x200.jpg",
    username: "vinayisactive",
    comment: "Upon my return from a short break every time,  I consistently find innovative additions by you✨🤌🏻",
    blue_tick: false,
    fullname: "Vinay",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1748932533298077696/wtZXz7du_200x200.jpg",
    username: "torytang025",
    comment: "Amazing, why are you so productive 🫡",
    blue_tick: false,
    fullname: "YOLO ツ",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1357549707279687681/uvgVa4bR_200x200.jpg",
    username: "Joe_Mifsud",
    comment: "These look awesome, nice work!",
    blue_tick: true,
    fullname: "Joe Mifsud",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1923971076276502528/uw7iJX4A_200x200.jpg",
    username: "MarkKnd",
    comment: "You can’t imagine how much time I spent to find the flashlight effect. Super useful!",
    blue_tick: true,
    fullname: "Mark Vassilevskiy",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1716079605147373568/Uwj4eD_H_200x200.jpg",
    username: "Srejitk",
    comment: "So happy to see @mannupaaji work being recognised 🥹🤌🏻♥️\n\nHis work is literally a treasure trove for devs 💎",
    blue_tick: false,
    fullname: "sreejith",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1835467796282499072/fY5hW09o_200x200.jpg",
    username: "deifosv",
    comment: "This component are 🔥\ngreat work",
    blue_tick: true,
    fullname: "Vlad",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/2053528056816349184/g5awJ6fv_200x200.jpg",
    username: "dnaijatechguy",
    comment: "Aceternity UI has some of the best components for designing landing pages I've ever seen. \n\nIf you're struggling with figuring out what animations to use. Check it out.\n\nThank me later 😉.\n\nui.aceternity.com",
    blue_tick: true,
    fullname: "Design Chief Priest",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1688244239832915968/om91VUkg_200x200.jpg",
    username: "EseMonday1",
    comment: "There are level to this things \n\nCongratulations @mannupaaji 👏🏾👏🏾",
    blue_tick: false,
    fullname: "EseMonday.eth | Devrel 🥑",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1688244239832915968/om91VUkg_200x200.jpg",
    username: "EseMonday1",
    comment: "This is bc amazing 👏🏾👏🏾👏🏾",
    blue_tick: false,
    fullname: "EseMonday.eth | Devrel 🥑",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1830860950401888256/CnFx1wfg_200x200.jpg",
    username: "geeky_dan",
    comment: "@aceternitylabs is just awesome, added some of its elements in my portfolio website",
    blue_tick: true,
    fullname: "Dhanush Vardhan Kalaiselvan",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1620828954767626241/NQpxz0Fy_200x200.jpg",
    username: "indievish",
    comment: "Well done Manu\nYou rock 🚀",
    blue_tick: true,
    fullname: "vish",
  },
  {
    profile_image: "https://pbs.twimg.com/profile_images/1940830276734627840/DuLEcvXI_200x200.jpg",
    username: "sandeep_indie",
    comment: "I do highly recommend checking out ui.aceternity.com/components by @mannupaaji \n\nIt's greaaaat!",
    blue_tick: true,
    fullname: "Sandeep",
  },
];
