import type { Tweet } from "./tweet";

/* Real tweets scraped from ui.aceternity.com's community wall (placeholder
   content until Lunar Studio has its own) — avatars served from Twitter's CDN. */
export const TWEETS: Tweet[] = [
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "NikhilPrashar_",
    fullname: "Nikhil Prashar",
    blue_tick: false,
    comment: "Excited",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "dhruvsood05",
    fullname: "Dhruv Sood",
    blue_tick: false,
    comment: "LESS GOOOO 🚀",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "saikiran29_x",
    fullname: "saikiran",
    blue_tick: false,
    comment: "looking forward. All the best 🤝",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "hiteshdotcom",
    fullname: "Hitesh Choudhary",
    blue_tick: true,
    comment: "Great start 👏",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "surajtwt",
    fullname: "Suraj Jha",
    blue_tick: true,
    comment: "Amazing! bss mehnat nhi rukni chhiye baaki aacha hi hoga",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "dhruvsood05",
    fullname: "Dhruv Sood",
    blue_tick: true,
    comment: "lesss gooo G 🚀",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "NikhilPrashar_",
    fullname: "Nikhil Prashar",
    blue_tick: false,
    comment: "Great",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "anandxdj",
    fullname: "Anand",
    blue_tick: false,
    comment: "🔥🔥",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "vishesh_dev_22",
    fullname: "Vishesh Kumawat",
    blue_tick: false,
    comment: "Congratulations Sagar! You're doing really cool stuff",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "shwetanigam_dev",
    fullname: "Shweta Nigam",
    blue_tick: false,
    comment: "Good luck! You got this!",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "Aditya989746994",
    fullname: "Aditya Panchal",
    blue_tick: false,
    comment: "Great start 🔥",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "HappyNegi1221",
    fullname: "Happy Negi",
    blue_tick: false,
    comment: "Great work 🔥",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "prashsainidev",
    fullname: "Prashant Saini",
    blue_tick: false,
    comment: "Nice bro keep it up !!",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "abhijitWebDev",
    fullname: "abhijitWebDev",
    blue_tick: true,
    comment: "Amazing !!",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "gopalchoudharry",
    fullname: "Gopal Choudhary",
    blue_tick: false,
    comment: "Let's Go 🚀",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "Sudhanshu7428",
    fullname: "Sudhanshu",
    blue_tick: false,
    comment: "👏👏",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "MehulArora121",
    fullname: "Mehul_Arora",
    blue_tick: false,
    comment: "💯",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "vishal_codeX",
    fullname: "Vishal",
    blue_tick: false,
    comment: "🔥🔥",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "ankur_hustler_ankur",
    fullname: "Ankur",
    blue_tick: false,
    comment: "nice name!",
  },
  {
    profile_image: "https://x.com/sagar__kemble",
    username: "AyushGhosh20864",
    fullname: "Ayush Ghosh",
    blue_tick: false,
    comment: "looking great",
  },
];
