import type { Metadata } from "next";

import {
  LegalPage,
  type LegalSection,
} from "@/components/sections/legal/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy — Lunar Studio",
  description:
    "How Lunar Studio collects, uses, and protects your personal information.",
};

const SECTIONS: LegalSection[] = [
  {
    id: "information-we-collect",
    heading: "Information We Collect",
    body: (
      <>
        <p>We collect information in the following ways:</p>
        <ul>
          <li>
            <strong>Information you give us.</strong> When you fill out our
            contact form, request a proposal, or email us, we collect your
            first name, last name, email address, and the details of your
            inquiry.
          </li>
          <li>
            <strong>Project information.</strong> During an engagement, you may
            share access to systems, documents, or data needed to deliver the
            work. We only collect what is necessary for the project.
          </li>
          <li>
            <strong>Usage data.</strong> We automatically collect anonymous
            information about how you use our website, such as pages visited,
            referring URLs, browser type, and approximate location derived from
            your IP address.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "how-we-use-information",
    heading: "How We Use Your Information",
    body: (
      <>
        <p>We use the information we collect to:</p>
        <ul>
          <li>Respond to your inquiries and send you a confirmation email.</li>
          <li>Prepare proposals, scope work, and deliver our services.</li>
          <li>Send service-related communications about your project.</li>
          <li>Improve our website and understand how it is used.</li>
          <li>Comply with our legal and contractual obligations.</li>
        </ul>
        <p>
          We do not sell your personal information, and we do not use it for
          automated decision-making that produces legal effects.
        </p>
      </>
    ),
  },
  {
    id: "cookies",
    heading: "Cookies & Tracking Technologies",
    body: (
      <>
        <p>
          Our website uses a small number of cookies and similar technologies
          to keep the site functioning and to measure aggregate, anonymised
          usage. You can disable cookies through your browser settings; some
          parts of the site may not work as intended if you do.
        </p>
      </>
    ),
  },
  {
    id: "how-we-share",
    heading: "How We Share Information",
    body: (
      <>
        <p>
          We share information only with trusted service providers who help us
          operate, and only to the extent necessary. These include:
        </p>
        <ul>
          <li>
            <strong>Email delivery</strong> — to send the confirmation and
            notification emails generated by our contact form.
          </li>
          <li>
            <strong>Hosting &amp; infrastructure</strong> — to serve this
            website and store project data securely.
          </li>
        </ul>
        <p>
          We may also disclose information where required by law or to protect
          our rights. We never sell, rent, or trade your personal information.
        </p>
      </>
    ),
  },
  {
    id: "data-retention",
    heading: "Data Retention",
    body: (
      <p>
        We keep personal information only as long as necessary for the purposes
        described in this policy — to respond to your inquiry, deliver a
        project, and meet our legal obligations. When it is no longer needed, we
        delete or anonymise it.
      </p>
    ),
  },
  {
    id: "data-security",
    heading: "Data Security",
    body: (
      <p>
        We protect your information with industry-standard measures, including
        encryption in transit (TLS), access controls on a least-privilege
        basis, and regular review of who can access what. No method of
        transmission or storage is completely secure, but we work to protect
        your data and to respond promptly if an issue arises.
      </p>
    ),
  },
  {
    id: "your-rights",
    heading: "Your Rights",
    body: (
      <>
        <p>
          Depending on where you live, you may have the right to:
        </p>
        <ul>
          <li>Access the personal information we hold about you.</li>
          <li>Correct inaccurate or incomplete information.</li>
          <li>Request deletion of your information.</li>
          <li>Receive a copy of your data in a portable format.</li>
          <li>Object to or restrict certain processing.</li>
          <li>Withdraw consent at any time, where processing relies on it.</li>
        </ul>
        <p>
          To exercise any of these rights, email us at{" "}
          <a href="mailto:privacy@lunarstudio.com">privacy@lunarstudio.com</a>.
        </p>
      </>
    ),
  },
  {
    id: "international-transfers",
    heading: "International Data Transfers",
    body: (
      <p>
        We may process and store information in countries other than your own.
        Where we transfer personal data internationally, we take steps to
        ensure it remains protected in line with this policy and applicable
        law.
      </p>
    ),
  },
  {
    id: "children",
    heading: "Children's Privacy",
    body: (
      <p>
        Our services are intended for businesses and individuals aged 18 and
        over. We do not knowingly collect personal information from children. If
        you believe a child has provided us information, please contact us so we
        can remove it.
      </p>
    ),
  },
  {
    id: "third-party-links",
    heading: "Third-Party Links",
    body: (
      <p>
        Our website may link to third-party sites we do not control. We are not
        responsible for their content or privacy practices, and we encourage
        you to review their policies before sharing information with them.
      </p>
    ),
  },
  {
    id: "changes",
    heading: "Changes to This Policy",
    body: (
      <p>
        We may update this Privacy Policy from time to time. When we do, we will
        revise the &quot;Last updated&quot; date above. Significant changes will
        be highlighted on this page.
      </p>
    ),
  },
  {
    id: "contact",
    heading: "Contact Us",
    body: (
      <>
        <p>
          If you have questions about this Privacy Policy or how we handle your
          information, reach out to us:
        </p>
        <ul>
          <li>
            General: <a href="mailto:hello@lunarstudio.com">hello@lunarstudio.com</a>
          </li>
          <li>
            Privacy: <a href="mailto:privacy@lunarstudio.com">privacy@lunarstudio.com</a>
          </li>
        </ul>
      </>
    ),
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy Policy"
      lastUpdated="June 13, 2026"
      intro={
        <p>
          This Privacy Policy explains how <strong>Lunar Studio</strong> (&quot;we&quot;,
          &quot;us&quot;, or &quot;our&quot;) collects, uses, and protects your information when
          you visit our website or work with us. By using our website or
          engaging our services, you agree to the practices described here.
        </p>
      }
      sections={SECTIONS}
    />
  );
}
